# Workflow to build and push the static hugo files to Cachix
name: 🛫 Build and push to Cachix

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: qgis-org
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#qgis-website 
    - run: nix flake check