name: Update Nix Flake inputs

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Update flakes and commit changes
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # This will allow us to trigger other workflows (cachix-build, etc.)
          # when we commit changes using the git-auto-commit-action
          token: ${{ secrets.PAT }}

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Run nix flake update
        run: >
          nix flake update

      - name: '✉️ Commit'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Flakes updated and committed via a GitHub Action.'

